set_property SRC_FILE_INFO {cfile:G:/git/AdComputadoras_2019/Tp4_MIPSIV/Constraint_Arquitectura_De_Computadoras.xdc rfile:../../../../../Constraint_Arquitectura_De_Computadoras.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports reset]
